//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApplication.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCity
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int CityId { get; set; }
        public bool IsFavourite { get; set; }
    
        public virtual City City { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
