//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApplication.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherCache
    {
        public int Id { get; set; }
        public int CityId { get; set; }
        public string WeatherIcon { get; set; }
        public string WeatherDescription { get; set; }
        public double Temperature { get; set; }
        public double FeelsLike { get; set; }
        public double UvIndex { get; set; }
        public double Pressure { get; set; }
        public string ObservationTime { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual City City { get; set; }
    }
}
